export const recipes = [
  {
    id: 1,
    type: 'recipe',
    title: 'Big and Juicy Wagyu Beef Cheeseburger',
    cookingTime: '30 Minutes',
    category: 'Snack',
    imgSrc: '',
  },
  {
    id: 2,
    type: 'recipe',
    title: 'Fresh Lime Roasted Salmon with Ginger Sauce',
    cookingTime: '30 Minutes',
    category: 'Fish',
    imgSrc: '',
  },
  {
    id: 3,
    type: 'recipe',
    title: 'Strawberry Oatmeal Pancake with Honey Syrup',
    cookingTime: '30 Minutes',
    category: 'Breakfast',
    imgSrc: '',
  },
  {
    id: 4,
    type: 'recipe',
    title: 'Fresh and Healthy Mixed Mayonnaise Salad',
    cookingTime: '30 Minutes',
    category: 'Healthy',
    imgSrc: '',
  },
  {
    id: 5,
    type: 'recipe',
    title: 'Chicken Meatballs with Cream Cheese',
    cookingTime: '30 Minutes',
    category: 'Meat',
    imgSrc: '',
  },
  {
    id: 6,
    type: 'banner',
  },
  {
    id: 7,
    type: 'recipe',
    title: 'Fruity Pancake with Orange & Blueberry',
    cookingTime: '30 Minutes',
    category: 'Sweet',
    imgSrc: '',
  },
  {
    id: 8,
    type: 'recipe',
    title: 'The Best Easy One Pot Chicken and Rice',
    cookingTime: '30 Minutes',
    category: 'Snack',
    imgSrc: '',
  },
  {
    id: 9,
    type: 'recipe',
    title: 'The Creamiest Creamy Chicken and Bacon Pasta',
    cookingTime: '30 Minutes',
    category: 'Noodles',
    imgSrc: '',
  },
]
